#!/bin/bash

iface="wlp2s0"
bssid=`iw dev $iface link | grep SSID | cut -f2 -d" " | tr -d \n`
ip=`ip address show $iface | grep "inet " | tr -s " " | cut -f3 -d" " | tr -d \n`

if [ "x$bssid" == "x" ]; then
    echo "<span color='red' weight='bold'>[NOT CONNECTED]</span>"
else
    echo "<span color='blue' weight='bold'>[$bssid]</span> <span color='cyan'>$ip</span>"
fi